### ISSUE TITLE
Sequence of clicks breaks interface

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Penguins#59]
The following sequence breaks the classification interface and causes the site to be unusable without a refresh; multiple users have reported it.

1. Click  "yes" that there are penguins, and "ok."
2. Mark at least one penguin.
3. Click the "back" button (in the interface, not the browser).
4. Click "no" and "ok."

The interface will break. This probably shouldn't happen; can we fix it?

**Comment by brian-c** [comment]
I won't get this any time soon either, sorry.

I could be totally off here, but my guts think this is a problem in the show-counts override. I think it thinks it's entering a drawing task when it's not.

https://github.com/zooniverse/Penguins/blob/master/show-counts.coffee#L20

The marking surface and the decision tree are not really in sync, so this thing is just kinda taped on there.

Super quick fix would be to hide the back button. It's only three steps.

**Comment by eatyourgreens** [comment]
I'm doing some work with readymade for the BHL, Wellcome and Retina projects, so I can have a look at this if you'd like.

**Comment by eatyourgreens** [comment]
BHL has the same bug, so it's in readymade. ClassifyPage.composeAnnotations() throws an 'undefined is not an object' error when it tries to save the marking surface tools to an annotation for a task that doesn't exist.
https://github.com/zooniverse/zooniverse-readymade/blob/master/src/classify-page.coffee#L210

I'll have a look at this tomorrow.
