### ISSUE TITLE
"Other" animal dropdown not working on iPads

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Penguins#60]
Multiple people are reporting that the dropdown menu for selecting an "other" animal on Penguin Watch is not working with classifications done on an iPad. It seems like the dropdown menu appears, but nothing is selectable. Apparently this worked before, but has just stopped working now.

"They say it was working before. Yes, they confirm their choice with the OK button but no Other animals seem to be counted."

http://talk.penguinwatch.org/#/subjects/APZ0001u2d

http://talk.penguinwatch.org/#/boards/BPZ0000001/discussions/DPZ000065k?page=1&comment_id=54bb8b66832cec389a00002f

Can we address this? Thanks!!

**Comment by brian-c** [comment]
If it broke recently, there might be an old version of a library being loaded somewhere. I'd get zooniverse/zooniverse-readymade#20 merged and published, reload Penguins's dependencies from npm, and redeploy.

**Comment by eatyourgreens** [comment]
I just checked this on my iPad and could select from the menu for other animals. Maybe it's fixed in iOS 8?

**Comment by eatyourgreens** [comment]
I've redeployed the site, with updated dependencies as per @brian-c's advice.

Closing this but feel free to re-open if the problem persists.
