### ISSUE TITLE
Change last "OK" to "Finish"

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Penguins#61]
Users have requested that the "OK" button be changed to "FINISH" at the point where clicking it will complete the classification, so that it is very clear when clicking it is a point of no return.

To quote a user on Talk: *I am teaching people on my account. People have a tendency to click "Adults" and then to immediately click "OK" rather than moving the cursor to the photo to start marking. If you changed that button to read "Done" or "Done Marking" I think that would keep people on track.*

After some discussion, we decided that "Finish" would be the best term.

Could we do this to make it clearer?

Thank you!!

**Comment by brian-c** [comment]
I won't be able to tackle this for quite a while. Some notes if you reassign it:

I'd merge zooniverse/zooniverse-readymade#20 and add a translation for that button text, then assign that translation as `confirmButtonLabel` when instantiating the DecisionTree on the classify page.

https://github.com/zooniverse/zooniverse-readymade/blob/allow-full-translation/src/classify-page.coffee#L53

**Comment by eatyourgreens** [comment]
I've updated the button labels in 7f78353d339f449174c0ca15d784b9d098ef0d8c

**Comment by eatyourgreens** [comment]
I'v e merged the translation branch into master on zooniverse-readymade too. Bumped the version to 0.6.3 but it needs to be published to npm.

**Comment by eatyourgreens** [comment]
I've deployed this to http://demo.zooniverse.org/penguins so you can check it @DarrenMcRoy 

@brian-c the classify page's onActivate() method is calling Subject.next() in the latest readymade. If you leave the classifier, eg. look at your user profile, and go back, you lose any classification in progress because a new subject loads.

**Comment by DarrenMcRoy** [comment]
Thanks so much, @eatyourgreens! Reopening with a couple more related requests:

1. Can the button in the marking section (the second state, where you actually click on the image) also be changed to "Finished Marking"? Apparently, that was the real problem (my fault for not understanding it), although what has been added is really helpful, too.

2. Less important, but still perhaps helpful: Can the "OK" button in the first stage of classifying change to "Finish" if you select "no animals" or "I can't tell," since that ends the classification?

Thank you!!
