### ISSUE TITLE
Able to "complete classification" by just clicking "OK" immediately

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Penguins#63]
At the moment, a user who immediately clicks "OK" without selecting "yes/no/can't tell" first is just told that they have completed their classification.

Similarly, a user can click "FINISH" without selecting either "marked every penguin" or "too many to mark."

Probably shouldn't be able to hit these without selecting something first?

**Comment by eatyourgreens** [comment]
We can fix the first one by making the answer default to yes.

Is there a default answer for the other question?

**Comment by DarrenMcRoy** [comment]
I guess it would be "I have marked every penguin." Although I fear that defaults might make people not fully consider the question they're being asked. But I'm probably overthinking it. :-)

**Comment by caitlinblack** [comment]
I would prefer the default to be "there are too many penguins to mark," if possible.

**Comment by DarrenMcRoy** [comment]
Scientist preference overrules me by far. :-) Too many penguins it is, unless it's possible to just make the button not work until you actually select one or the other. That would probably be the best.

**Comment by eatyourgreens** [comment]
I've set default values for those questions.

**Comment by DarrenMcRoy** [comment]
Good by me for now. Thanks!
