### ISSUE TITLE
Add link to FAQs to classifiction interface

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Penguins#66]
Can we add an FAQs link somewhere in the PW classification interface--similar to how Higgs Hunters and Science Gossip have done?

Here's the link: [edited, see below]

Thanks!!

**Comment by camallen** [comment]
@chrissnyder do you have time to do this?

**Comment by DarrenMcRoy** [comment]
The link has changed. Please use this link, whoever can do this!

http://talk.penguinwatch.org/#/boards/BPZ0000007

**Comment by chrissnyder** [comment]
I don't have time, sorry.
