### ISSUE TITLE
Task details popups are always in English

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Penguins#79]
Task detail language strings don't refresh when the language changes, so details popups eg. 'Other animals' are always in the default language, en-US.

**Comment by yshish** [comment]
Just a suggestion, but couldn't it be the same problem as was in the PP? There was the pop-up in the classification in English too. I think @srallen solved it?

**Comment by srallen** [comment]
It's was a race condition in Plankton Portal. The DOM was being loaded before the translations. The t7e library does have a refresh method, so I called that after the render to fix it for the inline tutorial. Check out https://github.com/zooniverse/plankton/commit/76f12461f8714b0de8bcd83496077900d275c3c3#diff-673b8cdd3d405beaed45e508b5d74e54R126

**Comment by eatyourgreens** [comment]
Thanks. It's more-or-less the same problem here. Those strings are stored in the project config, so they aren't in the DOM when the language changes. Calling `t7e.refresh()` after the popup opens fixes it.
