### ISSUE TITLE
Seeding translations fails on require in en-us.coffee

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Penguins#80]
Seeding new translation strings is failing on this section of the english language file, where it loads in 2 markdown files for the science page content.

```
science: "
    <section>#{require '../content/science'}</section>
    <section>#{require '../content/science-sidebar'}</section>
```

Do you remember how we got around this error before, @chrissnyder ?

**Comment by chrissnyder** [comment]
I reconstructed the file whole en-us manually and used a curl command to POST the resultant json to the API.

My recommendation here would just be to bring everything into en-us and be done with it.

**Comment by eatyourgreens** [comment]
Yes, I generated the science page HTML from the markdown, pasted it into the en-us file and ran deploy-locale. 

Merging everything into en-us makes sense to me. Unless there was a pressing reason to have that page in markdown.

**Comment by chrissnyder** [comment]
Just easy formatting I think, nothing else.
