### ISSUE TITLE
Firefox issues

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Penguins#81]
As reported by @yshish

> More details here: http://talk.penguinwatch.org/#/subjects/APZ0008qmw
It seems to be a problem with Firefox. 
I tried it just before letting you know and I had the same problems as mentioned.
Now when I classify, I don't get that broken last question (as visible in the 2nd screenshot) any more. But it is only because none of the images I get has any comment so that sentence about comments doesn't display at all. I wasn't lucky enough to get another image which would have some comments to see it again. I asked and they confirmed that the broken text displays only at commented pictures.
Oh, and they are complaining about the Other animals pop-up flashing in the top left corner before displaying where they click.

![error others photos missing](https://cloud.githubusercontent.com/assets/735191/10976407/4946b8be-83b1-11e5-8d48-506c2f11d5cd.png)
![error number of comments missing](https://cloud.githubusercontent.com/assets/735191/10976408/49470206-83b1-11e5-8bac-ffaf7c44d23d.jpg)

**Comment by yshish** [comment]
We got some reports from Chrome users as well! 
Details here:
http://talk.penguinwatch.org/#/subjects/APZ0004us3

**Comment by eatyourgreens** [comment]
Sounds like the Talk API is either timing out *or* the request for the comments isn't authenticating properly. @parrish was looking at a Talk problem yesterday which might be related.

**Comment by yshish** [comment]
OK. And I forgot to mention that the Other animals pop-up flashes in the top left corner before it appears in the correct place (where you click). I did experienced it in Chromium, others in Firefox. This was happening about half a year ago. Could it be related to that Talk API timing out?

**Comment by eatyourgreens** [comment]
This sounds like a different bug. The pop-up is displaying before the browser has calculated where the mouse was clicked, which is annoying.

Science Gossip uses the same code as Penguin Watch. Have you seen the pop-up boxes appear in the top left there too?

**Comment by yshish** [comment]
Yes! I use mainly Firefox where this doesn't happen to me (neither in PW, nor elsewhere) but I have just run SG in Chromium (where it happens for PW) and did see it flash in the top left corner before it displayed where I clicked!

A similar problem (but perhaps a different issue?) is in the PP, where you need to mark a plankton anywhere in the right half of the image, the pop-up first appear on the right side of the organism and then skip to the left! It has to change the position to don't go out of the image if the organism was to close to the image margin. But this is very annoying and when the computer is slower, it takes about 1 sec (or longer) before the pop-up changes the position, so you click on it when it moves, which makes a new mark there! People keep complaining it's annoying.

**Comment by yshish** [comment]
(Shall I create a new issue for PP? Or is it somewhere? Or is it unsolvable?)

**Comment by eatyourgreens** [comment]
I've opened zooniverse/zooniverse-readymade#34 about the popup appearing in the wrong place.

I'm not familiar with the code for Plankton Portal, but probably best to open issues about that on the plankton repository.

**Comment by yshish** [comment]
Thanks. Then I will open it.
