### ISSUE TITLE
Getting 502 Bad Gateway for PW Talk (and on the Zooniverse status page)

### ISSUE THREAD

**Issue by yshish** [zooniverse/Penguins#83]
The other PW Talk moderators have just reported me having troubles loading the Talk, getting 502 Bad Gateway. They can classify but not comment, they can't see any pages except Home and Classify. They went to Zooniverse to check if a problem had been reported, signed in fine but clicking on the link to the new Status Page leads to the following:
*502 Bad Gateway
nginx/1.4.6 (Ubuntu)*

I tried loading the Talk myself and it seems to be working without any problems for me but when I tried to load the [Zooniverse status page]()https://status.zooniverse.org/ it showed me errors with 502 Bad Gateway too. Here's a screenshot of my browser console:

![](https://lh3.googleusercontent.com/-tSPSlFuyBQU/VudA0em0fdI/AAAAAAAAIz4/ZPUZR1i7Mi0ja5rQuUrEtB55qq_-JyjlwCCo/s0-Ic42/ysh_2016-03-14_23-50-19.png)

Please, can you tell what's going on? 

Thanks.

**Comment by camallen** [comment]
Hi @yshish there were 2 problems, 1 the status page was down and 2 we misconfigured our site when migrating to run over https. We're working on it and. 

Please re-open if we haven't fixed this soon.

**Comment by yshish** [comment]
Thanks, Cam. All seems to be working again  :+1:

**Comment by yshish** [comment]
Not sure it is the same issue but the mod has just sent me a message 

>I can't use any pages on PW that are using Talk again.

But it seems to be working for me (I had no troubles yesterday either.)

**Comment by camallen** [comment]
hmm - force reload on the browser? http://refreshyourcache.com/en/cache/

**Comment by yshish** [comment]
Her reply:

>PW Talk works for me at the moment. Yesterday it would work sometimes, but not others... It's nothing to do with my browser or my cache - I dump that regularly.

Let's hope it won't break again.
